# Automaton Core Smart protocols

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "smartproto",
  srcs = [
    "smart_protocol.cc",
  ],
  hdrs = [
    "smart_protocol.h",
  ],
  deps = [
    "//automaton/core/data",
    "//automaton/core/data/protobuf",
    "//automaton/core/io",
    "@json//:json",
  ],
)
