package(default_visibility = ["//visibility:public"])

cc_library(
  name = "lua_node",
  srcs = [
    "lua_node.cc",
  ],
  hdrs = [
    "lua_node.h",
  ],
  deps = [
    "//automaton/core/data",
    "//automaton/core/data/protobuf",
    "//automaton/core/io",
    "//automaton/core/node:node",
    "//automaton/core/script",
    "//automaton/core/smartproto",
  ],
  linkstatic=True,
)
