# Automaton scripting library tests

package(default_visibility = ["//visibility:public"])

cc_test(
  name = "test_script",
  srcs = ["test_script.cc",],
  deps = [
    "//automaton/core/script",
    "@gtest//:gtest_main",
  ],
  linkstatic = True,
  size = "small",
)
