cc_test (
	name = "testnet",
	srcs = ["test.cc",],
  size = "medium",
	deps = [
    "//automaton/core/network:network_tcp",
    "//automaton/core/smartproto",
    "//automaton/core/node",
    "//automaton/core/testnet",
    "@gtest//:gtest_main",
  ],
)
