cc_test(
    name = "miner",
    srcs = ["miner_test.cc"],
    size = "small",
    deps = [
      "//automaton/tools/miner:miner_lib",
      "//automaton/core/io",
      "@gtest//:gtest_main",
    ],
)
