# Automaton Core Node

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "testnet",
  srcs = [
    "testnet.cc",
  ],
  hdrs = [
    "testnet.h",
  ],
  deps = [
    "//automaton/core/io",
    "//automaton/core/node",
  ],
  linkstatic=True,
)
