
cc_test(
    name = "test_ed25519_orlp",
    srcs = ["test_ed25519_orlp.cc"],
    size = "medium",
    deps = [
      "//automaton/core/crypto",
      "//automaton/core/crypto/cryptopp",
      "//automaton/core/crypto/ed25519_orlp",
      "@gtest//:gtest_main",
      "@ed25519_orlp//:ed25519_orlp",
    ],
)

cc_test(
    name = "test_crypto",
    srcs = ["test_hash_transformation.cc"],
    size = "medium",
    deps = [
      "//automaton/core/crypto",
      "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "sha_test",
    srcs = ["test_SHA256_cryptopp.cc"],
    size = "medium",
    deps = [
      "//automaton/core/crypto",
      "//automaton/core/crypto/cryptopp",
      "//automaton/core/io",
      "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "RIPEMD160_test",
    srcs = ["test_RIPEMD160_cryptopp.cc"],
    size = "medium",
    deps = [
      "//automaton/core/crypto",
      "//automaton/core/crypto/cryptopp",
      "//automaton/core/io",
      "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "SHA512_test",
    srcs = ["test_SHA512_cryptopp.cc"],
    size = "medium",
    deps = [
      "//automaton/core/crypto",
      "//automaton/core/crypto/cryptopp",
      "//automaton/core/io",
      "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "Keccak_256_test",
    srcs = ["test_Keccak_256_cryptopp.cc"],
    size = "medium",
    deps = [
      "//automaton/core/crypto",
      "//automaton/core/crypto/cryptopp",
      "//automaton/core/io",
      "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "SHA3_256_test",
    srcs = ["test_SHA3_256_cryptopp.cc"],
    size = "medium",
    deps = [
      "//automaton/core/crypto",
      "//automaton/core/crypto/cryptopp",
      "//automaton/core/io",
      "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "secp256k1_cryptopp",
    srcs = ["test_secp256k1_cryptopp.cc"],
    size = "medium",
    deps = [
      "//automaton/core/crypto",
      "//automaton/core/crypto/cryptopp",
      "//automaton/core/io",
      "@gtest//:gtest_main",
    ],
)
