# Automaton examples - easylogging++

package(default_visibility = ["//visibility:public"])

# cc_binary(
#   name = "demo_log",
#   srcs = [
#     "demo_log.cc",
#   ],
#   deps = [
#     "//automaton/core/io",
#   ],
# )
