
# Automaton Core common module

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "status",
  srcs = [
    "status.cc",
  ],
  hdrs = [
    "status.h",
  ],
  linkstatic=True,
)
