# Automaton I/O utility library

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "io",
  srcs = [
    "blob.cc",
    "io.cc",
  ],
  hdrs = [
    "blob.h",
    "io.h",
  ],
  deps = [
    "@g3log//:g3log",
  ],
  linkstatic=1,
)
