# LOCALLY BUILD THIRD PARTY LIBRARIES

new_local_repository(
  name = "replxx",
  path = "local_third_party/replxx",
  build_file = "third_party/replxx.BUILD",
)

new_local_repository(
  name = "libzmq",
  path = "local_third_party/libzmq",
  build_file = "third_party/libzmq.BUILD",
)

new_local_repository(
  name = "luajit",
  path = "local_third_party/LuaJIT/src",
  build_file = "third_party/LuaJIT.BUILD",
)

new_local_repository(
  name = "cppzmq",
  path = "local_third_party/cppzmq",
  build_file = "third_party/cppzmq.BUILD",
)

new_local_repository(
  name = "sol",
  path = "local_third_party/sol2/single/sol",
  build_file = "third_party/sol2.BUILD",
)

new_local_repository(
  name = "easyloggingpp",
  path = "local_third_party/easyloggingpp/src",
  build_file = "third_party/easyloggingpp.BUILD",
)

new_local_repository(
  name = "ed25519_orlp",
  path = "local_third_party/ed25519/src",
  build_file = "third_party/ed25519_orlp.BUILD",
)

local_repository(
  name = "gtest",
  path = "local_third_party/googletest",
  # build_file = "local_third_party/gtest.BUILD",
)

local_repository(
  name = "com_google_protobuf",
  path = "local_third_party/protobuf",
)

new_local_repository(
  name = "cryptopp",
  path = "local_third_party/cryptopp",
  build_file = "third_party/cryptopp.BUILD",
)

new_local_repository(
  name = "bitcoin",
  path = "local_third_party/bitcoin-0.16.0",
  build_file = "third_party/bitcoin.BUILD",
)

new_local_repository(
  name = "lua",
  path = "local_third_party/lua",
  build_file = "third_party/lua.BUILD",
)

new_local_repository(
  name = "com_github_glog_glog",
  path = "local_third_party/glog-0.3.5",
  build_file = "third_party/glog.BUILD",
)

new_local_repository(
  name = "di",
  path = "local_third_party/di-1.0.2/include",
  build_file = "third_party/di.BUILD",
)

new_local_repository(
  name = "json",
  path = "local_third_party/json-3.1.2",
  build_file = "third_party/json.BUILD",
)

# Local Bazel ready builds

local_repository(
  name = "com_github_gflags_gflags",
  path = "local_third_party/gflags-2.2.1",
)

new_local_repository(
  name = "localboost",
  path = "local_third_party/boost",
  build_file = "third_party/localboost.BUILD",
)
